name: sensors_example
description: Demonstrates how to use the sensors plugin.

dependencies:
  flutter:
    sdk: flutter
  sensors:
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  e2e:
    path: ../../e2e
  pedantic: ^1.8.0
  sqflite: ^1.1.6
  path_provider: ^1.2.0
  path: ^1.6.2
  http: ^0.12.2




flutter:
  uses-material-design: true

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.9.1+hotfix.2 <2.0.0"

